version: 2.1

executors:
  docker-circleci:
    working_directory: "~/repo"
    docker:
      - image: "circleci/node:10.12-stretch-browsers"

commands:
  checkout_install_bootstrap:
    steps:
      - checkout
      - run: npm ci --ignore-scripts
      - run: npm run bootstrap

jobs:
  unit_integration_test:
    executor: docker-circleci
    steps:
      - checkout_install_bootstrap
      - run: npm test

  prepare_release:
    executor: docker-circleci
    steps:
      - checkout_install_bootstrap
      - run: npm run lint
      - run: npm build

workflows:
  build_test:
    jobs:
      - unit_integration_test
      - prepare_release
